name:                powerman
version:             0.1.0.0
github:              "fahadbr/powerman"
license:             MIT
author:              "Fahad Riaz"
maintainer:          "fahadbr@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fahadbr/powerman#readme>

dependencies:
- base >= 4.7 && < 5
- directory

library:
  source-dirs: src

executables:
  powerman:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerman

tests:
  powerman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerman
    - hspec
